In [2]:
import pandas as pd

In [36]:
#import the assembled data for training and forecast 
df_train = pd.read_csv(r'C:\Ember\PyPSA\demandcast\demandcast\demandcast\data\assembled\assembled_data_for_training_20260428_203235.csv') #data for training
df_fc = pd.read_csv(r'C:\Ember\PyPSA\demandcast\demandcast\demandcast\data\assembled\assembled_data_for_forecasting_20260428_204538.csv') #data for forecasting

In [4]:
df_train.head()

,Time (UTC),Annual electricity demand per capita (kWh),Entity code,GDP PPP per capita (2021 international $),Population,Local hour of the day,Local weekend indicator,Local month of the year,Local year,Temperature - Top 1 (K),Temperature - Top 3 (K),Monthly average temperature - Top 1 (K),Monthly average temperature rank - Top 1,Annual average temperature - Top 1 (K),5 percentile temperature - Top 1 (K),95 percentile temperature - Top 1 (K),Load (MW),Load (fraction of annual total)
0,2019-12-31 16:00:00,9373.253267,SGP,120396.237937,5703569.0,0.0,0.0,1.0,2020.0,298.99963,299.53824,300.25314,8.0,300.516,297.93677,304.20795,5641.682489,0.000106
1,2019-12-31 17:00:00,9373.253267,SGP,116288.627996,5685807.0,1.0,0.0,1.0,2020.0,298.81238,299.41177,300.25314,8.0,300.516,297.93677,304.20795,5536.415127,0.000104
2,2019-12-31 18:00:00,9373.253267,SGP,116288.627996,5685807.0,2.0,0.0,1.0,2020.0,298.77844,299.29382,300.25314,8.0,300.516,297.93677,304.20795,5438.140008,0.000102
3,2019-12-31 19:00:00,9373.253267,SGP,116288.627996,5685807.0,3.0,0.0,1.0,2020.0,298.62220,299.15472,300.25314,8.0,300.516,297.93677,304.20795,5271.877176,0.000099
4,2019-12-31 20:00:00,9373.253267,SGP,116288.627996,5685807.0,4.0,0.0,1.0,2020.0,298.44202,299.01883,300.25314,8.0,300.516,297.93677,304.20795,5163.171288,0.000097

In [5]:
df_fc.head()

,Time (UTC),Annual electricity demand per capita (kWh),Entity code,GDP PPP per capita (2021 international $),Population,Local hour of the day,Local weekend indicator,Local month of the year,Local year,Temperature - Top 1 (K),Temperature - Top 3 (K),Monthly average temperature - Top 1 (K),Monthly average temperature rank - Top 1,Annual average temperature - Top 1 (K),5 percentile temperature - Top 1 (K),95 percentile temperature - Top 1 (K)
0,2019-12-31 16:00:00,9373.253267,SGP,120396.237937,5703569.0,0.0,0.0,1.0,2020.0,298.99963,299.53824,300.25314,8.0,300.516,297.93677,304.20795
1,2019-12-31 17:00:00,9373.253267,SGP,116288.627996,5685807.0,1.0,0.0,1.0,2020.0,298.81238,299.41177,300.25314,8.0,300.516,297.93677,304.20795
2,2019-12-31 18:00:00,9373.253267,SGP,116288.627996,5685807.0,2.0,0.0,1.0,2020.0,298.77844,299.29382,300.25314,8.0,300.516,297.93677,304.20795
3,2019-12-31 19:00:00,9373.253267,SGP,116288.627996,5685807.0,3.0,0.0,1.0,2020.0,298.62220,299.15472,300.25314,8.0,300.516,297.93677,304.20795
4,2019-12-31 20:00:00,9373.253267,SGP,116288.627996,5685807.0,4.0,0.0,1.0,2020.0,298.44202,299.01883,300.25314,8.0,300.516,297.93677,304.20795

In [39]:
#import the forecast results 
df_results = pd.read_csv(r'C:\Ember\PyPSA\demandcast\demandcast\demandcast\ml_models\results\forecasts\with_xgboost_model_20260428_203244\using_assembled_data_for_forecasting_20260428_204538\all_20260428_204601.csv')
df_results.head()

C:\Users\vnhg1\AppData\Local\Temp\ipykernel_21960\2556268795.py:2: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_results = pd.read_csv(r'C:\Ember\PyPSA\demandcast\demandcast\demandcast\ml_models\results\forecasts\with_xgboost_model_20260428_203244\using_assembled_data_for_forecasting_20260428_204538\all_20260428_204601.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,0.019323389
0,Time (UTC),Entity code,Local hour of the day,Local weekend indicator,Local month of the year,Temperature - Top 1 (K),Temperature - Top 3 (K),Monthly average temperature - Top 1 (K),Monthly average temperature rank - Top 1,Annual average temperature - Top 1 (K),5 percentile temperature - Top 1 (K),95 percentile temperature - Top 1 (K),GDP PPP per capita (2021 international $),Annual electricity demand per capita (kWh),Local year,Forecast load (MW),NaN,% differences from training data
1,31/12/2019 16:00,SGP,0,0,1,298.99963,299.53824,300.25314,8,300.516,297.93677,304.20795,120396.2379,9373.253267,2020,5774.105457,NaN,0.023472248
2,31/12/2019 17:00,SGP,1,0,1,298.81238,299.41177,300.25314,8,300.516,297.93677,304.20795,116288.628,9373.253267,2020,5756.123793,NaN,0.039684283
3,31/12/2019 18:00,SGP,2,0,1,298.77844,299.29382,300.25314,8,300.516,297.93677,304.20795,116288.628,9373.253267,2020,5756.123793,NaN,0.058472894
4,31/12/2019 19:00,SGP,3,0,1,298.6222,299.15472,300.25314,8,300.516,297.93677,304.20795,116288.628,9373.253267,2020,5756.123793,NaN,0.091854685

In [40]:
df_results.columns = df_results.iloc[0]

In [ ]:
df_train = df_train[['Time (UTC)','Entity code','Load (MW)']]

                Time (UTC) Entity code    Load (MW)
0      2019-12-31 16:00:00         SGP  5641.682489
1      2019-12-31 17:00:00         SGP  5536.415127
2      2019-12-31 18:00:00         SGP  5438.140008
3      2019-12-31 19:00:00         SGP  5271.877176
4      2019-12-31 20:00:00         SGP  5163.171288
...                    ...         ...          ...
52603  2025-12-31 11:00:00         SGP  7189.638850
52604  2025-12-31 12:00:00         SGP  7101.195500
52605  2025-12-31 13:00:00         SGP  6990.700450
52606  2025-12-31 14:00:00         SGP  6784.926950
52607  2025-12-31 15:00:00         SGP  6558.908700

[52608 rows x 3 columns]

In [41]:
df_results = df_results[['Time (UTC)','Entity code','Forecast load (MW)']]

In [42]:
df_results = df_results[1:]

In [44]:
df_results['Time (UTC)'] = pd.to_datetime(df_results['Time (UTC)'])

C:\Users\vnhg1\AppData\Local\Temp\ipykernel_21960\2446182111.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_results['Time (UTC)'] = pd.to_datetime(df_results['Time (UTC)'])

In [46]:
df_train['Time (UTC)']=pd.to_datetime(df_train['Time (UTC)'])

In [50]:
df = pd.merge(df_train, df_results, on = ['Time (UTC)','Entity code'],how = 'left')

In [54]:
df['Load (MW)']=pd.to_numeric(df['Load (MW)'])

In [55]:
df['Forecast load (MW)']=pd.to_numeric(df['Forecast load (MW)'])

In [56]:
df['pct actual and forecast'] = abs((df['Load (MW)']-df['Forecast load (MW)'])/df['Forecast load (MW)'])

In [58]:
df['pct actual and forecast'].mean()

np.float64(0.05922389707334828)